# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
